name: worker_manager
version: 4.0.2
description: Executor allows you to create a queue of tasks for isolate pool
homepage: "https://github.com/Renesanse/worker_manager"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta:

dev_dependencies:
  lint: ^1.5.3
  test: ^1.17.3

