name: worker_manager
version: 6.3.1
description: The worker_manager allows you to manage CPU-intensive calculations across isolates
homepage: "https://github.com/Renesanse/worker_manager"

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  async: ^2.11.0
  collection: ^1.18.0
  meta: ^1.9.1
  uuid: 4.3.3

dev_dependencies:
  test: ^1.25.2

