name: worker_manager
version: 5.0.3
description: Executor allows you to create a queue of tasks for isolate pool
homepage: "https://github.com/Renesanse/worker_manager"

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  async: ^2.9.0
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1

